{
    "storeOrder": ["produce", "bread", "spreads", "deli", "dairy"],
    "itemList": [
        {
            "_id": 9, 
            "amountNumber": 1, 
            "amountStr": "2 loaves", 
            "amountUnits": null, 
            "estPrice": null, 
            "listId": 3, 
            "modified": "2010-10-26 18:11:58", 
            "name": "white bread", 
            "notes": null, 
            "price": null, 
            "section": "bread", 
            "status": 1
        }, 
        {
            "_id": 12, 
            "amountNumber": 1, 
            "amountStr": "1 jar", 
            "amountUnits": null, 
            "estPrice": null, 
            "listId": 3, 
            "modified": "2010-10-26 18:11:58", 
            "name": "raspberry jam", 
            "notes": "large bottle", 
            "price": null, 
            "section": "spreads", 
            "status": 0
        }, 
        {
            "_id": 8, 
            "amountNumber": 1, 
            "amountStr": "1 package", 
            "amountUnits": null, 
            "estPrice": null, 
            "listId": 3, 
            "modified": "2010-10-26 18:11:58", 
            "name": "sliced swiss cheese", 
            "notes": null, 
            "price": null, 
            "section": "deli", 
            "status": 0
        }, 
        {
            "_id": 6, 
            "amountNumber": 1, 
            "amountStr": "8", 
            "amountUnits": null, 
            "estPrice": null, 
            "listId": 3, 
            "modified": "2010-10-26 18:11:58", 
            "name": "oranges", 
            "notes": null, 
            "price": null, 
            "section": "produce", 
            "status": 0
        }, 
        {
            "_id": 10, 
            "amountNumber": 1, 
            "amountStr": "1 loaf", 
            "amountUnits": null, 
            "estPrice": null, 
            "listId": 3, 
            "modified": "2010-10-26 18:11:58", 
            "name": "wheat bread", 
            "notes": null, 
            "price": null, 
            "section": "bread", 
            "status": 0
        }, 
        {
            "_id": 11, 
            "amountNumber": 1, 
            "amountStr": "1 large jar", 
            "amountUnits": null, 
            "estPrice": null, 
            "listId": 3, 
            "modified": "2010-10-26 18:11:58", 
            "name": "peanut butter", 
            "notes": "creamy", 
            "price": null, 
            "section": "spreads", 
            "status": 0
        }, 
        {
            "_id": 7, 
            "amountNumber": 1, 
            "amountStr": "3", 
            "amountUnits": null, 
            "estPrice": null, 
            "listId": 3, 
            "modified": "2010-10-26 18:11:58", 
            "name": "avocados", 
            "notes": "one soft", 
            "price": null, 
            "section": "produce", 
            "status": 0
        },
        {
            "_id": 7, 
            "amountNumber": 1, 
            "amountStr": "5 or 6", 
            "amountUnits": null, 
            "estPrice": null, 
            "listId": 3, 
            "modified": "2010-10-26 18:11:58", 
            "name": "bananas", 
            "notes": null, 
            "price": null, 
            "section": "produce", 
            "status": 2
        }
    ]
}
